# add ec2 instance in inventory

- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
    - aws_credentials_keys.yml
  tasks:
    - name: Master EC2 Instances facts
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Name: "swarm_master_nodes"
      register: masterNodesEc2

    - name: Worker Nodes EC2 Instances facts
      ec2_instance_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Name: "swarm_worker_nodes"
      register: workerNodesEc2


    - name: add Master EC2 host to inventory
      add_host:
        hostname: '{{ item.public_ip_address }}'
        groupname: master_nodes
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: '{{ masterNodesEc2.instances }}'

    - name: add Worker Nodes EC2 host to inventory
      add_host:
        hostname: '{{ item.public_ip_address }}'
        groupname: worker_nodes
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: '{{ workerNodesEc2.instances }}'
